metadata:
  name: wit-db
  labels:
    service: wit-db
  annotations:
    configmap.fabric8.io/update-on-change: "wit"
spec:
  replicas: 1
  selector:
    service: wit-db
  template:
    metadata:
      labels:
        service: wit-db
    spec:
      containers:
      - image: registry.centos.org/postgresql/postgresql:9.6
        env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wit
              key: db.password
        imagePullPolicy: IfNotPresent
        name: wit-db
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql
          name: wit-postgresql-data
          readOnly: false
      volumes:
      - name: wit-postgresql-data
        persistentVolumeClaim:
          claimName: wit-postgresql-data