spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: fabric8/keycloak-postgres:${keycloak.version}
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        readinessProbe:
          httpGet:
            path: "/auth"
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: "/auth"
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/standalone/data
          name: keycloak-data
          readOnly: false
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data
