apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    expose.config.fabric8.io/apiserver-url-key: apiserver.url
    #expose.service-key.config.fabric8.io/sso: keycloak.url
data:
  keycloak.url: http://sso
  apiserver.url: http://kubernetes
