metadata:
  name: keycloak-db
  labels:
    service: keycloak-db
spec:
  replicas: 1
  selector:
    service: keycloak-db
  template:
    metadata:
      labels:
        service: keycloak-db
    spec:
      containers:
      - image: registry.centos.org/postgresql/postgresql:9.6
        env:
        - name: POSTGRESQL_DATABASE
          value: keycloak
        - name: POSTGRESQL_PASSWORD
          value: keycloak
        - name: POSTGRESQL_USER
          value: keycloak
        imagePullPolicy: IfNotPresent
        name: keycloak-db
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql
          name: keycloak-db-postgresql-data
          readOnly: false
      volumes:
      - name: keycloak-db-postgresql-data
        persistentVolumeClaim:
          claimName: keycloak-db-postgresql-data