spec:
  template:
    spec:
      containers:
      - image: registry.centos.org/postgresql/postgresql:9.6
        env:
        - name: POSTGRESQL_DATABASE
          value: keycloak
        - name: POSTGRESQL_PASSWORD
          value: keycloak
        - name: POSTGRESQL_USER
          value: keycloak
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql
          name: keycloak-postgresql-data
          readOnly: false
      volumes:
      - name: keycloak-postgresql-data
        persistentVolumeClaim:
          claimName: keycloak-postgresql-data